### PR TITLE
Added ability to create syncers for tvOS projects

### PR DESCRIPTION
**Pull request by voidrender**
This is enough to allow creation of syncers for tvOS targets. Bots are created and executed as expected--see [ioveracker/Zen PR #3](https://github.com/ioveracker/Zen/pull/3) for an example. 

There is still the issue of how to build both iOS and tvOS targets, or conditionally build one target or the other based on the PR title or something else. But for now, this will suffice for creating syncers that build tvOS projects.

### CODE REVIEW

**Comment by buildasaur** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/cc6638942eeca76b8e63719bed0185c0/cc6638942eeca76b8e63719bed019d11)
---
*Duration*: 30 seconds
*Result*: **-1 error, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/cc6638942eeca76b8e63719bed0185c0/cc6638942eeca76b8e63719bed0235fc)
---
*Duration*: 12 seconds
*Result*: **-1 error, failing state: trigger-error**

**Comment by buildasaur** [comment]
## Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/cc6638942eeca76b8e63719bed0185c0/cc6638942eeca76b8e63719bed026e5e)

_Duration_: 10 minutes and 34 seconds
_Result_: All 42 tests passed, but please **fix 1 warning**.

**Comment by czechboy0** [comment]
@ioveracker Thanks for taking the time to investigate! I'll make further changes to be able to run multiple syncers on the same branch and hopefully that should be enough to allow for testing on multiple platforms without the catch-all schemes.

If you do manage to test out the catch-all scheme, however, it would be great to know if that's also a viable solution usable with Xcode Server. Thanks!

**Comment by voidrender** [comment]
Excellent! I'll continue testing catch-all schemes and let you know if it works out.

**Pull request merged**
