### PR TITLE
Storing credentials in Keychain

### LINKED ISSUE #137: Password Storage
Currently credentials are stored in plain text.

Change to use the keychain instead.

### PR DESCRIPTION
**Pull request by czechboy0**
Fixes #137, #202.

Uses KeychainAccess wrapped in SwiftSafe to make it thread-safe. Works nicely.

### CODE REVIEW

**Comment by czechboy0** [comment]
There seems to be an issue on Xcode Server where the migration tests seem to be hanging. My guess is that it's a hanging keychain issue.

TODO: investigate whether to not use a fake keychain object for tests

**Comment by buildasaur** [comment]
## Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/988772e2f2b47c8fba527ed14f3d1aba/988772e2f2b47c8fba527ed14f41beb4)

_Duration_: 14 minutes and 51 seconds
Build was **manually canceled**.

**Comment by buildasaur** [comment]
## Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/988772e2f2b47c8fba527ed14f3d1aba/078af1d74a9639ddb9b9dc23f00040d7)

_Duration_: 14 minutes and 38 seconds
_Result_: **-1 error, failing state: internal-build-error**

**Comment by buildasaur** [comment]
## Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/988772e2f2b47c8fba527ed14f3d1aba/078af1d74a9639ddb9b9dc23f000a19b)

_Duration_: 3 minutes and 49 seconds
_Result_: **Perfect build!** All 35 tests passed. :+1:
_Test Coverage_: 24%

**Pull request merged**
