### PR TITLE
[WAITING] New source server support (BitBucket)

### PR DESCRIPTION
**Pull request by czechboy0**
started abstracting away the source server types so that we can hide more than just GitHub behind them. protocols ftw!

### CODE REVIEW

**Comment by buildasaur** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/969649f1529344fbcedaca78ad019eb1/969649f1529344fbcedaca78ad01a0db)
---
*Duration*: 1 hour, 15 seconds
*Result*: **-1 error, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/969649f1529344fbcedaca78ad019eb1/969649f1529344fbcedaca78ad01f846)
---
*Duration*: 3 minutes and 19 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by buildasaur** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/494523300873ac12496d00d3a900f58b/494523300873ac12496d00d3a9014e10)
---
*Duration*: 2 minutes and 57 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by buildasaur** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/494523300873ac12496d00d3a900f58b/494523300873ac12496d00d3a924f695)
---
*Duration*: 3 minutes and 9 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by buildasaur** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/494523300873ac12496d00d3a900f58b/494523300873ac12496d00d3a9255d85)
---
*Duration*: 4 minutes and 30 seconds
*Result*: **13 errors, failing state: build-errors**

**Comment by buildasaur** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/494523300873ac12496d00d3a900f58b/66f92b6d96c59a7870c00be955000e71)
---
*Duration*: 0 second
Build was **manually canceled**.

**Comment by buildasaur** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/494523300873ac12496d00d3a900f58b/4e84984fd804cb6675867cfeeb000705)
---
*Duration*: 0 second
Build was **manually canceled**.

**Comment by buildasaur** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/9dbf435dacd6a870f84de9a7cf024f81/9dbf435dacd6a870f84de9a7cf0274ba)
---
*Duration*: 4 minutes and 0 second
*Result*: **13 errors, failing state: build-errors**

**Comment by buildasaur** [comment]
## Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/9dbf435dacd6a870f84de9a7cf024f81/988772e2f2b47c8fba527ed14f344aa8)

_Duration_: 5 minutes and 14 seconds
_Result_: **Perfect build!** All 34 tests passed. :+1:
_Test Coverage_: 23%

**Comment by czechboy0** [comment]
I'd like to ship a version with Crashlytics first, so this branch will merge after we ship 0.7. Work here, together with #65 will be aimed at 0.8.

**Comment by buildasaur** [comment]
## Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/9dbf435dacd6a870f84de9a7cf024f81/988772e2f2b47c8fba527ed14f3d0f81)

_Duration_: 3 minutes and 37 seconds
_Result_: **Perfect build!** All 34 tests passed. :+1:
_Test Coverage_: 23%

**Comment by buildasaur** [comment]
## Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/9dbf435dacd6a870f84de9a7cf024f81/078af1d74a9639ddb9b9dc23f005752f)

_Duration_: 3 minutes and 44 seconds
_Result_: **Perfect build!** All 35 tests passed. :+1:
_Test Coverage_: 24%

**Pull request closed without merging**
