### PR TITLE
[WIP] Expected completion time descriptions

### PR DESCRIPTION
**Pull request by czechboy0**
Added expected remaining time to the github status descriptions to give a rough estimate of how much longer the build will take.

### CODE REVIEW

**Comment by buildasaur** [comment]
## Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/988772e2f2b47c8fba527ed14f2631bc/988772e2f2b47c8fba527ed14f263adf)

_Duration_: 5 minutes and 11 seconds
_Result_: **Perfect build!** All 36 tests passed. :+1:
_Test Coverage_: 23%

**Comment by buildasaur** [comment]
## Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/988772e2f2b47c8fba527ed14f2631bc/988772e2f2b47c8fba527ed14f2b9918)

_Duration_: 3 minutes and 50 seconds
_Result_: **Perfect build!** All 36 tests passed. :+1:
_Test Coverage_: 23%

**Comment by czechboy0** [comment]
Turns out that the `expectedCompletionDate` is only returned inside of integrations when they're queried by the new `/queue/integrations` API. However, when resolving actions, we use the regular `/bot/.../integrations` endpoint. There are multiple possible solutions:
- [ ] create a new endpoint in XcodeServerSDK for `/queue/integrations`, query that at the beginning of the sync and inject the estimated completion time into our integrations, if possible, then continue as normal
- refactor the resolution logic to first try to resolve with only queued integrations and only then querying for normal integrations if it's a 'sleeping' bot - thus we'd had the estimated completion time in our integrations right away.
- [x] file a bug report so that expected completion date is returned in the regular endpoint as well (_done: rdar://24261846_) - and wait till that happens, then just merge this PR (that what I assumed was happening before).

At the moment I'm leaning towards the first solution, because it's simpler and to the point. The second solution would make sense as a part of a large refactor, assuming the logic wouldn't get unnecessarily more complex.

Next steps:
- create endpoint for `/queue/integrations` and watch what they do with the endpoint during the Xcode 7.3 beta period (this only showed up in beta 1).
- if it gets into stable 7.3, use the first solution.

Until then, this PR is blocked.

**Comment by czechboy0** [comment]
Closing for now, there's nothing to do at the moment (waiting for Apple to hopefully fix this in the final Xcode 7.3)

**Pull request closed without merging**
