### PR TITLE
Multi-repo support

### LINKED ISSUE #1: Save triggers independently of build templates (for easy reuse)

### PR DESCRIPTION
**Pull request by czechboy0**
This mega PR is tracking the branch on which stuff is happening. Yes, multi-repo is now number 1 priority for me on Buildasaur. Will take a couple of days (also because I'm building it fully with ReactiveCocoa, which I'm just learning), but is on its way.

Feel free to subscribe to this PR and answer my questions about building apps with AppKit, which is just a PITA for me as an iOS developer.

Fixes #1, #12.

---

Checklist before merging:
- [x] profile Allocations and make sure all VCs are getting dealloc'd properly
- [x] ensure the migrator works from previous storage format to new
- [x] rename the persistence folder back to the original

### CODE REVIEW

**Comment by czechboy0** [comment]
Question 1: #139.

**Comment by buildasaur** [comment]
Result of Integration **1**
---
*Duration*: 3 minutes and 9 seconds
*Result*: All 19 tests passed, but please **fix 5 warnings**.
*Test Coverage*: 20%.

**Comment by buildasaur** [comment]
Result of Integration **2**
---
*Duration*: 2 minutes and 32 seconds
*Result*: All 19 tests passed, but please **fix 5 warnings**.
*Test Coverage*: 20%.

**Comment by buildasaur** [comment]
Result of Integration **3**
---
*Duration*: 2 minutes and 46 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by buildasaur** [comment]
Result of Integration **4**
---
*Duration*: 35 seconds
*Result*: **-1 error, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **5**
---
*Duration*: 2 minutes and 20 seconds
*Result*: All 19 tests passed, but please **fix 5 warnings**.
*Test Coverage*: 20%.

**Comment by buildasaur** [comment]
Result of Integration **6**
---
*Duration*: 8 hours, 37 minutes and 2 seconds
*Result*: **-1 error, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **7**
---
*Duration*: 2 minutes and 47 seconds
*Result*: All 19 tests passed, but please **fix 4 warnings**.
*Test Coverage*: 20%.

**Comment by buildasaur** [comment]
Result of Integration **8**
---
*Duration*: 2 minutes and 25 seconds
*Result*: All 19 tests passed, but please **fix 4 warnings**.
*Test Coverage*: 21%.

**Comment by buildasaur** [comment]
Result of Integration **9**
---
*Duration*: 2 minutes and 38 seconds
*Result*: All 19 tests passed, but please **fix 4 warnings**.
*Test Coverage*: 21%.

**Comment by buildasaur** [comment]
Result of Integration **10**
---
*Duration*: 2 minutes and 16 seconds
*Result*: All 19 tests passed, but please **fix 4 warnings**.
*Test Coverage*: 21%.

**Comment by buildasaur** [comment]
Result of Integration **11**
---
*Duration*: 2 minutes and 41 seconds
*Result*: All 19 tests passed, but please **fix 4 warnings**.
*Test Coverage*: 21%.

**Comment by buildasaur** [comment]
Result of Integration **12**
---
*Duration*: 14 seconds
*Result*: **-1 error, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **13**
---
*Duration*: 16 seconds
*Result*: **-1 error, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **14**
---
*Duration*: 15 seconds
*Result*: **-1 error, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **15**
---
*Duration*: 15 seconds
*Result*: **-1 error, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **1**
---
*Duration*: 23 seconds
*Result*: **-1 error, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **2**
---
*Duration*: 2 minutes and 32 seconds
*Result*: All 19 tests passed, but please **fix 4 warnings**.
*Test Coverage*: 21%.

**Comment by buildasaur** [comment]
Result of Integration **3**
---
*Duration*: 5 minutes and 46 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by buildasaur** [comment]
Result of Integration **4**
---
*Duration*: 3 minutes and 6 seconds
*Result*: **3 errors, failing state: build-errors**

**Comment by buildasaur** [comment]
Result of Integration **5**
---
*Duration*: 3 minutes and 36 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by buildasaur** [comment]
Result of Integration **6**
---
*Duration*: 2 minutes and 21 seconds
*Result*: All 19 tests passed, but please **fix 4 warnings**.
*Test Coverage*: 21%.

**Comment by buildasaur** [comment]
Result of Integration **3**
---
*Duration*: 2 minutes and 57 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by buildasaur** [comment]
## Result of Integration **1**

_Duration_: 3 minutes and 46 seconds
_Result_: **1 error, failing state: build-errors**

**Comment by buildasaur** [comment]
Result of Integration **3**
---
*Duration*: 3 minutes and 10 seconds
*Result*: **Build failed 2 tests** out of 21

**Comment by buildasaur** [comment]
Result of Integration **3**
---
*Duration*: 3 minutes and 10 seconds
*Result*: **Build failed 2 tests** out of 21

**Comment by buildasaur** [comment]
## Result of Integration **9**

_Duration_: 7 minutes and 19 seconds
_Result_: All 23 tests passed, but please **fix 2 warnings**.
_Test Coverage_: 21%.

**Comment by buildasaur** [comment]
Result of Integration **9**
---
*Duration*: 7 minutes and 19 seconds
*Result*: All 23 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 21%.

**Comment by buildasaur** [comment]
Result of Integration **9**
---
*Duration*: 7 minutes and 19 seconds
*Result*: All 23 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 21%.

**Comment by buildasaur** [comment]
Result of Integration **9**
---
*Duration*: 7 minutes and 19 seconds
*Result*: All 23 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 21%.

**Comment by buildasaur** [comment]
## Result of Integration **11**

_Duration_: 2 minutes and 51 seconds
_Result_: All 23 tests passed, but please **fix 2 warnings**.
_Test Coverage_: 21%.

**Comment by buildasaur** [comment]
Result of Integration **11**
---
*Duration*: 2 minutes and 51 seconds
*Result*: All 23 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 21%.

**Comment by buildasaur** [comment]
Result of Integration **11**
---
*Duration*: 2 minutes and 51 seconds
*Result*: All 23 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 21%.

**Comment by czechboy0** [comment]
Only took two weeks. :sweat: :laughing: :rocket:

**Pull request merged**
