### PR TITLE
Disable App Transport Security to connect to self-signed XCS

### PR DESCRIPTION
**Pull request by Brett-Best**
Added ATS key to Info PLISTs.

### CODE REVIEW

**Comment by buildasaur** [comment]
## Result of Integration **1**

_Duration_: 2 minutes and 3 seconds
_Result_: All 19 tests passed, but please **fix 3 warnings**.
_Test Coverage_: 23%.

**Comment by czechboy0** [comment]
Are you sure it needs to be added to _all_ the Info.plists? I think I tried adding it to just the Buildasaur (the app) target and that was enough. Please try to remove the rest and see whether it still works, thanks :+1:

**Comment by Brett-Best** [comment]
@czechboy0 on my local machine I had to add it all of them but the test targets. I added them to the test targets encase you added tests that would break depending on the server the were against.

**Comment by Brett-Best** [comment]
@czechboy0 looks like it only needed to be on the one target after all.

**Comment by buildasaur** [comment]
## Result of Integration **1**

_Duration_: 2 minutes and 17 seconds
_Result_: All 19 tests passed, but please **fix 3 warnings**.
_Test Coverage_: 23%.

**Comment by czechboy0** [comment]
Brilliant, thank you, @Brett-Best! :+1:

**Pull request merged**
