### PR TITLE
Adding Code Coverage and Test Number changes to comments

### LINKED ISSUE #75: Report code coverage in github comments
Pull code coverage information out of the build results and add it to the comment in the PR, so that users can see if a particular integration/PR is making code coverage better or worse.

### PR DESCRIPTION
**Pull request by czechboy0**
Fixes #75 and also adds comments for when tests are added and removed.

### CODE REVIEW

**Comment by buildasaur** [comment]
## Result of Integration **1**

_Duration_: 20 seconds
_Result_: **? errors, failing state: trigger-error**

**Comment by buildasaur** [comment]
## Result of Integration **2**

_Duration_: 15 seconds
_Result_: **? errors, failing state: trigger-error**

**Comment by buildasaur** [comment]
## Result of Integration **3**

_Duration_: 16 seconds
_Result_: **? errors, failing state: trigger-error**

**Comment by buildasaur** [comment]
## Result of Integration **4**

_Duration_: 1 minute and 43 seconds
_Result_: **Build failed 7 tests** out of 21

**Comment by buildasaur** [comment]
## Result of Integration **5**

_Duration_: 14 seconds
_Result_: **? errors, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **5**
---
*Duration*: 14 seconds
*Result*: **? errors, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **5**
---
*Duration*: 14 seconds
*Result*: **? errors, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **5**
---
*Duration*: 14 seconds
*Result*: **? errors, failing state: trigger-error**

**Comment by buildasaur** [comment]
Result of Integration **6**
---
*Duration*: 14 seconds
*Result*: **? errors, failing state: trigger-error**

**Comment by czechboy0** [comment]
Xcode 7 Beta 3 is being difficult, tests pass locally.

**Pull request merged**
