### PR TITLE
Remove Podfile.lock from the repo and ignore it

### PR DESCRIPTION
**Pull request by alimoeeny**

### CODE REVIEW

**Comment by buildasaur** [comment]
## Result of Integration **1**

_Duration_: 2 minutes and 26 seconds
_Result_: All 19 tests passed, but please **fix 3 warnings**.
_Test Coverage_: 23%.

**Comment by czechboy0** [comment]
What's your reasoning behind removing it? I like the `Podfile.lock` being checked in because it ensures that if you go to a certain version of the code and run `pod install`, you always get the same version of the dependencies as were when that version of the code was being developed. If you remove the `Podfile.lock`, suddenly the dependencies are not tied to the code any more and will always be the most recent ones. 

Have you had an issue with `Podfile.lock` being checked in?

**Comment by alimoeeny** [comment]
It maybe a matter of taste. But in my mind if you care about the version of a dependency, you put it in the `Podfile` itself. If you don't then you don't put it there. 
Having the podfile.lock in the repo just looks untidy to me. like checking in .swp files into a repo. 
But hey, this is totally your decision. if you like it the way it is, keep it the way it is.

**Comment by czechboy0** [comment]
I followed the instructions from the CocoaPods people, see section about Podfile.lock in this guide: http://guides.cocoapods.org/using/using-cocoapods.html

**Comment by alimoeeny** [comment]
Thank you. All clear. Closing the PR.

**Comment by czechboy0** [comment]
:+1:

**Pull request closed without merging**
